package se.ju.student.hihe1788.laderappen2

import java.util.*

/**
 * A file that states all constants.
 */

// Mower related UUID's
val MOWER_SERVICE_UUID = UUID.fromString("0000ffe1-0000-1000-8000-00805f9b34fb")
var MOWER_SERVICE_ALTERNATIVE_UUID: UUID = UUID.fromString("9e5d1e47-5c13-43a0-8635-82ad38a1386f")
val MOWER_CHARACTERISTIC_READ_UUID = UUID.fromString("0000ffe2-0000-1000-8000-00805f9b34fb")
val MOWER_CHARACTERISTIC_WRITE_UUID = UUID.fromString("0000ffe3-0000-1000-8000-00805f9b34fb")
val DESCRIPTOR_UUID = UUID.fromString("00002902-0000-1000-8000-00805f9b34fb")
val APP_UUID = UUID.fromString("0a1bb95f-c32e-4718-92a8-0b88c25b1035")

// GATT related ACTIONS
const val ACTION_GATT_CONNECTED = BuildConfig.APPLICATION_ID+".ACTION_GATT_CONNECTED"
const val ACTION_GATT_DISCONNECTED = BuildConfig.APPLICATION_ID+".ACTION_GATT_DISCONNECTED"
const val ACTION_GATT_SERVICES_DISCOVERED = BuildConfig.APPLICATION_ID+".ACTION_GATT_SERVICES_DISCOVERED"
const val ACTION_GATT_DATA_AVAILABLE = BuildConfig.APPLICATION_ID+".ACTION_DATA_AVAILABLE"
const val ACTION_DATA_WRITTEN = BuildConfig.APPLICATION_ID+".ACTION_DATA_WRITTEN"
const val ACTION_GATT_REGISTER_CHARACTERISTIC_READ = BuildConfig.APPLICATION_ID+".ACTION_GATT_REGISTER_CHARACTERISTIC_READ"
const val GATT_EXTRA_DATA = BuildConfig.APPLICATION_ID+".GATT_EXTRA_DATA"

// ACTIONS FOR COMMUNICATING TO AND FROM MOWER
const val ACTION_DATA_RECEIVED_FROM_MOWER = "100"
const val ACTION_SEND_LIGHTS = "101"
const val ACTION_SEND_HONK = "102"
const val ACTION_SEND_QUIT = "103"
const val ACTION_SEND_AUTO = "104"
const val ACTION_SEND_MANUAL = "105"
const val ACTION_CONNECT_TO_MOWER = "106"
const val ACTION_SEND_ACK_TO_MOWER = "107"

// DATABASE ID's
const val COLLISION_AVOIDANCE_POINT = 3
const val POSITION_POINT = 5

const val OFFICIAL_DOC_ANDROID_DEVELOPER = "https://developer.android.com/docs"

